name             'workstation'
maintainer       'David Goerger'
maintainer_email 'david.goerger@yale.edu'
source_url       'https://git.deowyth.blog/dgoerger/workstation'
issues_url       'https://git.deowyth.blog/dgoerger/workstation/issues'
description      'Fedora Workstation'
long_description 'Configures Fedora Workstation for general computer lab use.'
license          'ISC'
supports         'fedora'
version          '3.0.0'
