# recommended: limit to 77 char (3char lead in template)  'START                                                                    END'
default['workstation']['_motd']['greeting']              = '                                Welcome!'
default['workstation']['_motd']['announcements']         = 'ANNOUNCEMENTS: none'
default['workstation']['_motd']['errata']                = ''
default['workstation']['_motd']['reboot_cycle_text']     = 'REBOOT CYCLE: '
