# recommended: limit to 77 char (3char lead in template)  'START                                                                    END'
default['workstation']['motd']['greeting']              = '                           Welcome to the Zoo!'
default['workstation']['motd']['announcements']         = 'ANNOUNCEMENTS: none'
default['workstation']['motd']['errata']                = ''
default['workstation']['motd']['reboot_cycle_text']     = 'REBOOT CYCLE: '
